anki_word_adder/apps/accounts/urls.py
from django.urls import path

from .views import RegisterView, LoginLearnerView, LogoutView, SettingsView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginLearnerView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('settings/', SettingsView.as_view(), name='settings'),
]

anki_word_adder/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import MainPageView, GuidePageView, VersionsPageView, GetWordDataView, FeedbackView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('account/', include('anki_word_adder.apps.accounts.urls')),

    path('', MainPageView.as_view(), name='main'),

    path('guide/', GuidePageView.as_view(), name='guide'),

    path('versions/', VersionsPageView.as_view(), name='versions'),

    path('word-data/<str:word>', GetWordDataView.as_view(), name='word_data'),

    path('feedback/', FeedbackView.as_view(), name='feedback'),
]

templates/base.html
<!-- Includes base resources and defines base blocks to override for every other template:
1) 'title' for the page's title
2) 'head' to allow child templates to add other scripts and styles into the head
3) 'body' for the main content
-->

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <Title>{% block title %} Anki Word Adder {% endblock %}</Title>

  {% block head %}{% endblock %}

  <link rel="icon" href="{% static 'images/anki.png' %}">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  <!-- Custom styles -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

  <!-- JavaScript Bundle with Popper -->
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
</head>

<body style="background-color: #eee">
  {% block body %}{% endblock %}
</body>

</html>

templates/base_authentication.html
<!-- Base template for login and registration page with a 'user_form' block for login/registration -->
{% extends "./base.html" %}
{% load static %}

{% block body %}
<main class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-6">
      <div class="card rounded-4 overflow-hidden bg-light">
        <div class="row">

          <section class="col p-4">
            <div class="text-center">
              <img class="authentication-image" src="{% static 'images/anki.png' %}" alt="Anki">
              <h4 class="mb-3">Anki Word Adder</h4>
            </div>

            {% block user_form %}
            {% endblock %}
          </section>

          <section class="col p-4 d-flex align-items-center gradient">
            <div class="text-white">
              <h4>Better way of learning words</h4>
              <p class="small mt-4">
                Anki Word Adder leverages the power of Anki and multiple APIs
                to help you learn new words faster and with much less manual work!
                Read the <b><a href="{% url 'guide' %}" class="link-secondary font-size-large">guide</a></b> before
                you start
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/base_error.html
{% extends "./base_navbar.html" %}
{% load static %}


{% block title %}
Ooops
{% endblock %}

{% block head %}
<script defer src="{% static 'js/homer_eyes.js' %}" type="module"></script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col d-flex flex-column justify-content-center align-items-center">
    <p class="display-6">
      Ooops, something went wrong. <br>
      Error code: {% block error %} {% endblock %}. <br>
    </p>
  </div>

  <div class="col-auto">
    <img src="{% static 'images/homer_thinking.png' %}" id="homer" alt="Homer">
    <img class="eye" src="{% static 'images/eye.png' %}" alt="Eye"
      style="position: relative; top: -90px; left: -238px; width: 40px;">
    <img class="eye" src="{% static 'images/eye.png' %}" alt="Eye"
      style="position: relative; top: -93px; left: -201px; width: 40px;">
  </div>
</div>
{% endblock %}

templates/base_navbar.html
<!-- Adds top and bottom navbars to the base template and defines 'content' block -->
{% extends "./base.html" %}
{% load static %}

{% block body %}

<!-- Top navbar -->
<nav class="navbar fixed-top navbar-dark bg-dark">
  <div class="container">
    <div>
      <a class="navbar-brand" href="{% url 'main' %}">
        <img class="nav-image" src="{% static 'images/AWA.png' %}" height="30" alt="AWA">
        <img class="nav-image" src="{% static 'images/anki.png' %}" height="30" alt="Anki">
      </a>
      <a class="nav-link-top" href="{% url 'guide' %}">Guide</a>
      <a class="nav-link-top m-2" href="{% url 'versions' %}">What's new</a>
    </div>

    {% if user.is_authenticated %}
    <div class="nav-item dropdown">
      <button class="btn btn-secondary gradient" id="profileDropdown" role="button" data-bs-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        {{user.username.0}}
      </button>
      <div class="dropdown-menu" aria-labelledby="profileDropdown">
        <h6 class="dropdown-header">{{user.username}}</h6>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'accounts:settings' %}">Settings</a>
        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
      </div>
    </div>
    {% endif %}
  </div>
</nav>

<!-- Main content -->
<div class="container my-3 py-5">
  <div id="message-container">
    <!-- Messages may come from backend -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
  </div>
  <main>
    {% block content %}{% endblock %}
  </main>
</div>

<!-- Feedback modal -->
{% if user.is_authenticated %}
<div class="modal fade" id="feedback-modal" tabindex="-1" role="dialog" aria-labelledby="feedback-modal-label"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="feedback-modal-label">Feedback</h5>
      </div>
      <div class="modal-body">
        <p>
          Please, tell about your expirience with AWA (things that you like or dislike so far, or features you want
          to see in the future). Leave your email if you need a reply.
        </p>
        <textarea class="form-control" id="feedback-area" rows="5"></textarea>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-primary" id="send-button" data-bs-dismiss="modal" type="submit" disabled>Send</button>
      </div>
    </div>
  </div>
</div>
{% endif %}

<!-- Bottom navbar -->
<nav class="navbar fixed-bottom navbar-dark bg-dark">
  <div class="container">
    <div>

      <a class="hvr-float" href="https://github.com/MihailGusev/anki_word_adder" target="_blank" title="Source code">
        <img class="nav-icon-bottom" src="{% static 'images/github.png' %}" alt="GitHub">
      </a>

      {% if user.is_authenticated %}
      <input class="hvr-float nav-icon-bottom" type="image" src="{% static 'images/message.png' %}"
        data-bs-toggle="modal" data-bs-target="#feedback-modal" title="Send feedback">
      </input>
      {% endif %}
    </div>

    <span class="text-end" style="color: gainsboro;">www.Collinsdictionary.com © HarperCollins Publishers Ltd
      2014</span>
  </div>
</nav>

<!-- Script to enable/disable 'Send feedback button' -->
{% if user.is_authenticated %}
<script src="{% static 'js/feedback.js' %}" type="module"></script>
{% endif %}

{% endblock %}

templates/guide.html
{% extends "./base_navbar.html" %}
{% load static %}

{% block title %}
Guide
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-12 col-lg-11 col-xl-10">
    <section>
      <h4>What is Anki?</h4>
      <p>
        If you do not know what Anki is, <a href="https://apps.ankiweb.net/" target="_blank">check it out</a> first.
        In short, Anki is a program that uses a special technique to help you remember information.
      </p>
    </section>

    <section>
      <h4>What is Anki Word Adder?</h4>
      <p>
        Anki Word Adder (AWA) connects to your Anki application and allows you to create cards for
        learning new words in a couple of clicks. Card example:
        <img class="card-image" src="{% static 'images/card_example.png' %}" alt="Card example">
      </p>
    </section>

    <section>
      <h4>Limitations</h4>
      AWA is a fresh project, so it has some limitations that may be removed later on:
      <ul>
        <li>AWA <b>cannot be used on mobile devices</b>, because it depends on AnkiConnect add-on and add-ons
          are only available on Windows, Mac and Linux.</li>
        <li>AWA may be <b>unavailable at the end of each month</b>, because of the free hosting time limit</li>
        <li>AWA <b>can only create cards for English words</b>. If you want support for other languages,
          you may send feedback after registration</li>
      </ul>
    </section>

    <section>
      <h4>How to use AWA</h4>
      <div class="mx-3">
        <h6>Setup</h6>

        <ol>
          <li>
            Install <a href="https://apps.ankiweb.net/" target="_blank">Anki</a>
          </li>

          <li>
            Install <a href="https://ankiweb.net/shared/info/2055492159">AnkiConnect</a> addon.
            It allows AWA to communicate with Anki
            <br />
            <ol>
              <li>In your Anki application go to the 'Tools' menu</li>
              <li>Click 'Add-ons'</li>
              <li>In the opened window click 'Get Add-ons'</li>
              <li>Copy and paste '2055492159' (without quotes) inside the 'code' field and click 'OK'</li>
              <li>Restart Anki</li>
            </ol>
          </li>

          <li>
            Open AWA's <a href="{% url 'main' %}">main page</a>
            <br />
            <ol>
              <li>Anki will ask you to allow access to it. Click 'Yes'.</li>
              <li>In AWA choose a deck, where your AWA cards will be stored and click 'Select'</li>
            </ol>
          </li>
        </ol>

        <h6>Usage</h6>
        <ol>
          <li>Type English word inside 'Word' field</li>
          <li>Put the context in which the word was found inside the 'Context' field
            (for example a sentence in a book you're reading). You can skip it, but
            I highly recommend not to do it because
            adding your unique context to the word helps to remember it
          </li>
          <li>Click 'Get information' button (or press enter inside the 'Word' field) and wait until translations
            and other information is downloaded</li>
          <li>Click 'Create card' button</li>
        </ol>

        <h6>Changing the style of the cards</h6>
        If you're an experienced user, you may want to change the look of the cards by
        <a href="https://docs.ankiweb.net/templates/styling.html">changing</a>
        the templates for front and back sides of the card as well as additional styling.
        The one thing you better <b>not to do</b> is changing field names or deleting them. AWA
        creates a new note type if it cannot find all the fields it needs.
      </div>

    </section>
  </div>
</div>

{% endblock %}

templates/login.html
{% extends "./base_authentication.html" %}

{% block title %}
Login
{% endblock %}

{% block user_form %}
<form method="post">
  {% csrf_token %}

  {{ form.non_field_errors }}

  {% for field in form %}
  <div class="form-floating p-2">
    {{ field }}
    {{ field.label_tag }}
  </div>
  {{ field.errors }}
  {% endfor %}

  <div class="p-2">
    <input class="btn btn-primary btn-lg w-100 gradient" id="submit" type="submit" value="Login">
  </div>
</form>

<div class="text-center mt-3">
  New user? <a href="{% url 'accounts:register' %}">Register</a>
</div>
{% endblock %}

templates/main.html
{% extends "./base_navbar.html" %}
{% load static %}

{% block head %}
<!-- Pass user information into javascript -->
{{ learner_settings|json_script:"learner-settings"}}

<link rel="stylesheet" href="{% static 'css/floating_label_fix.css' %}" />
<script defer src="{% static 'js/main.js' %}" type="module"></script>
{% endblock %}


{% block content %}
<!-- Show when deck-id for the user couldn't be found in anki's decks -->
<div class="hidden" id="deck-selection-controls">
  <div class="input-group">
    <label class="input-group-text" for="deck-select">Select a deck which will store your new cards</label>
    <select class="form-select" id="deck-select"></select>
    <button class="btn btn-primary" id="submit-deck-id">Select</button>
  </div>
</div>


<!-- When everything is OK - show main controls -->
<div id="card-adding-controls" class="hidden">
  <div class="form-floating my-2">
    <input class="form-control" id="word-field" type="text" placeholder="Word">
    <label for="word-field">Word</label>
  </div>

  <div class="form-floating my-2">
    <textarea class="form-control context-text-area" id="context" placeholder="Context"></textarea>
    <label for="context">Context</label>
  </div>

  <!-- Translation table -->
  <div class="card container my-2">
    <div class="card-header row">
      <div class="col">
        <h5>Translations</h5>
      </div>
      <div class="col-md-5 col-lg-4 col-xl-3">
        <div class="text-end">
          <select class="form-select" id="frequency-filter-select">
            <option value="1">All</option>
            <option value="2">Common and uncommon</option>
            <option value="3">Only common</option>
          </select>
        </div>
      </div>
    </div>

    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Part of speech</th>
            <th scope="col">Translation</th>
            <th scope="col">Reverse translations</th>
            <th scope="col">Frequency</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody id="translation-table-body">
          <!-- Rows are inserted from JS-->
        </tbody>
      </table>
    </div>
  </div>

  <!-- Definition table -->
  <div class="card container my-2">
    <div class="card-header row">
      <div class="col">
        <h5>Definitions</h5>
      </div>
      <div class="col">
        <div class="text-end">
          <input class="form-check-input" type="checkbox" id="show-google-definitions">
          <label class="form-check-label" for="show-google-definitions">Google</label>

          <input class="form-check-input" type="checkbox" id="show-collins-definitions">
          <label class="form-check-label" for="show-collins-definitions">Collins</label>
        </div>
      </div>
    </div>

    <div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Part of speech</th>
            <th scope="col">Definition</th>
            <th scope="col">Examples</th>
            <th scope="col">Synonyms</th>
            <th scope="col">Tags</th>
            <th scope="col">Source</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody id="definition-table-body">
          <!-- Rows are inserted from JS-->
        </tbody>
      </table>
    </div>
  </div>

  <!-- Buttons and links -->
  <div class="row my-2">
    <div class="col">
      <button class="btn btn-primary" id="get-info-button" type="button" disabled>
        Get information
      </button>
      <button class="btn btn-primary" id="create-card-button" type="button" disabled>Create card</button>
    </div>

    <div class="col-5 text-end">
      <a id="google-link" target="_blank">Google</a>
      <a id="collins-link" target="_blank">Collins</a>
      <a id="cambridge-link" target="_blank">Cambridge</a>
      <a id="oxford-link" target="_blank">Oxford</a>
    </div>
  </div>

</div>
{% endblock %}

templates/register.html
{% extends "./base_authentication.html" %}

{% block title %}
Register
{% endblock %}

{% block user_form %}
<form method="post">
  {% csrf_token %}

  {{ form.non_field_errors }}

  {% for field in form %}
  <div class="form-floating p-2">
    {{ field }}
    {{ field.label_tag }}
  </div>
  {{ field.errors }}
  {% endfor %}

  <div class="p-2">
    <input class="btn btn-primary btn-lg w-100 gradient" id="submit" type="submit" value="Register">
  </div>
</form>

<div class="text-center mt-3">
  Already have an account? <a href="{% url 'accounts:login' %}">Login</a>
</div>
{% endblock %}

templates/settings.html
{% extends "./base_navbar.html" %}
{% load static %}

{% block title %}
Settings
{% endblock %}

{% block head %}
<!-- Pass settings into javascript -->
{{ settings|json_script:"settings"}}
<script defer src="{% static 'js/settings.js' %}" type="module"></script>
{% endblock %}

{% block content %}
<div class="col-md-6 col-lg-5 col-xl-4 hidden" id="settings-container">
  <div class="input-group my-2">
    <label class="input-group-text" for="select-language">Translate English to</label>
    <select class="form-select" id="select-language"></select>
  </div>

  <div class="input-group my-2">
    <label class="input-group-text" for="select-deck">Put cards into</label>
    <select class="form-select" id="select-deck"></select>
  </div>

  <div class="my-2">
    <input class="form-check-input" id="show-message-on-card-addition" type="checkbox">
    <label for="show-message-on-card-addition">Show message when card is added to Anki</label>
  </div>

  <button class="btn col-12 btn-primary my-1" id="button-save">Save</button>

</div>

{% endblock %}

templates/versions.html
{% extends "./base_navbar.html" %}

{% block title %}
What's new
{% endblock %}

{% block content %}

<div class="row justify-content-center">
  <div class="col-md-12 col-lg-11 col-xl-10">
    <section>
      <h4>Version 0.9 (public testing, English only)</h4>
      <h6>Features:</h6>
      <ul>
        <li>Showing translations of English words into the language selected by the user (Google Translate)</li>
        <li>Showing definitions of English words (Google Translate and Collins' American-learner dictionary)</li>
        <li>Filtering translations by their frequency </li>
        <li>Filtering definitions by their source (Google or Collins) </li>
        <li>Deleting unnecessary translations and definitions </li>
        <li>Creating new Anki cards via AnkiConnect using:
          <ul>
            <li>English word and context provided by the user</li>
            <li>Filtered translations and definiitons</li>
            <li>Transcription and pronunciation sound taken from Collins</li>
          </ul>
        </li>
      </ul>
    </section>
  </div>
</div>

{% endblock %}